# Generated by Django 3.0.5 on 2020-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_class',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
