# Generated by Django 3.0.5 on 2020-04-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genius', '0005_auto_20200416_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gurdian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField(null=True)),
                ('emerg_name', models.CharField(max_length=200, null=True)),
                ('emerg_contact', models.CharField(max_length=20)),
                ('emerg_relation', models.CharField(max_length=20)),
                ('doc_name', models.CharField(max_length=200, null=True)),
                ('doc_contact', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=10)),
                ('allergic', models.TextField(null=True)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(choices=[('G1', 'Grade-1'), ('G2', 'Grade-2'), ('G3', 'Grade-3'), ('G4', 'Grade-4'), ('G5', 'Grade-5'), ('G6', 'Grade-6'), ('G7', 'Grade-7'), ('G8', 'Grade-8'), ('G9', 'Grade-9'), ('G10', 'Grade-10'), ('G11', 'Grade-11'), ('G12', 'Grade-12')], max_length=10)),
                ('attending_school', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('course', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genius.Create_Class')),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genius.Gurdian')),
            ],
        ),
    ]
