# Generated by Django 3.0.5 on 2020-04-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0006_gurdian_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gurdian',
            name='allergic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gurdian',
            name='doc_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gurdian',
            name='emerg_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gurdian',
            name='emerg_relation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('G1', 'Grade-1'), ('G2', 'Grade-2'), ('G3', 'Grade-3'), ('G4', 'Grade-4'), ('G5', 'Grade-5'), ('G6', 'Grade-6'), ('G7', 'Grade-7'), ('G8', 'Grade-8'), ('G9', 'Grade-9'), ('G10', 'Grade-10'), ('G11', 'Grade-11'), ('G12', 'Grade-12')], max_length=10, null=True),
        ),
    ]
