# Generated by Django 3.0.5 on 2020-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0007_auto_20200418_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurdian',
            name='allergic',
            field=models.TextField(null=True),
        ),
    ]
