# Generated by Django 3.0.5 on 2020-04-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0008_auto_20200418_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='students',
            name='allergic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='blood_type',
            field=models.CharField(choices=[('O', 'O'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('A+', 'A+'), ('AB', 'AB')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='doc_contact',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='doc_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='emerg_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='emerg_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='emerg_relation',
            field=models.CharField(choices=[('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Father', 'Father'), ('Mother', 'Mother'), ('Grandpa', 'Grandpa'), ('Grandma', 'Grandma'), ('Sister', 'Sister'), ('Brother', 'Brother')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='attending_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Gurdian',
        ),
    ]
