# Generated by Django 3.0.5 on 2020-04-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0009_auto_20200421_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='students',
            name='doc_contact',
            field=models.CharField(default='None', max_length=20, verbose_name='Doctor Contact'),
        ),
        migrations.AlterField(
            model_name='students',
            name='doc_name',
            field=models.CharField(default='None', max_length=200, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='emerg_contact',
            field=models.CharField(max_length=20, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='students',
            name='emerg_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Emergency Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='emerg_relation',
            field=models.CharField(choices=[('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Father', 'Father'), ('Mother', 'Mother'), ('Grandpa', 'Grandpa'), ('Grandma', 'Grandma'), ('Sister', 'Sister'), ('Brother', 'Brother')], max_length=20, null=True, verbose_name='Emergency Relationship'),
        ),
    ]
