# Generated by Django 3.0.3 on 2020-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0010_auto_20200422_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
