# Generated by Django 3.0.5 on 2020-05-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0011_students_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField(null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('MMK', 'Kyats')], max_length=50, null=True)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('KBZ_Pay', 'KBZ Pay')], max_length=50, null=True)),
                ('remind_date', models.DateField(null=True)),
                ('comment', models.TextField()),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genius.Students')),
            ],
        ),
    ]
