# Generated by Django 3.0.5 on 2020-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_class',
            name='cost',
            field=models.CharField(default=300, max_length=50, null=True),
        ),
    ]
