# Generated by Django 3.0.3 on 2020-04-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0012_auto_20200430_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
    ]
