# Generated by Django 3.0.5 on 2020-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0014_payment_left_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remind_date',
            field=models.DateField(default=None),
        ),
    ]
