# Generated by Django 3.0.5 on 2020-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0015_auto_20200501_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
