# Generated by Django 3.0.5 on 2020-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0016_stdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Stdimage',
        ),
    ]
